# Generated by Django 6.1 on 2026-09-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_batchsale_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchsale',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
